package com.multi0819.facilityreport;
import android.app.*;import android.os.*;import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.provider.MediaStore;import android.webkit.*;import android.widget.Toast;import android.util.Base64;import java.io.*;
public class MainActivity extends Activity {
 private WebView web;private ValueCallback<Uri[]> files;private GeolocationPermissions.Callback geo;private String geoOrigin;
 private static final String ORIGIN="https://appassets.androidplatform.net";
 @Override public void onCreate(Bundle state){super.onCreate(state);web=new WebView(this);web.setBackgroundColor(0xff081321);setContentView(web);web.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets bars=insets.getInsets(android.view.WindowInsets.Type.systemBars());v.setPadding(bars.left,bars.top,bars.right,bars.bottom);return insets;});WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setGeolocationEnabled(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.addJavascriptInterface(new Bridge(),"ReportAndroid");
 web.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest req){Uri u=req.getUrl();if("appassets.androidplatform.net".equals(u.getHost())){try{String p=u.getPath();if(p==null||p.contains(".."))throw new IOException();InputStream in=getAssets().open(p.equals("/")?"index.html":p.substring(1));return new WebResourceResponse(p.endsWith(".html")?"text/html":"application/octet-stream","UTF-8",in);}catch(IOException e){return new WebResourceResponse("text/plain","UTF-8",404,"Not Found",null,new ByteArrayInputStream(new byte[0]));}}return null;}
 @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest req){if(ORIGIN.equals(req.getUrl().getScheme()+"://"+req.getUrl().getHost()))return false;String scheme=req.getUrl().getScheme();if("https".equals(scheme)||"http".equals(scheme)||"kakaotalk".equals(scheme)){try{startActivity(new Intent(Intent.ACTION_VIEW,req.getUrl()));}catch(Exception e){toast("연결할 앱이 없습니다");}}return true;}});
 web.setWebChromeClient(new WebChromeClient(){@Override public boolean onJsAlert(WebView v,String u,String m,JsResult r){new AlertDialog.Builder(MainActivity.this).setMessage(m).setPositiveButton("확인",(d,x)->r.confirm()).setOnCancelListener(d->r.cancel()).show();return true;}@Override public boolean onJsConfirm(WebView v,String u,String m,JsResult r){new AlertDialog.Builder(MainActivity.this).setMessage(m).setPositiveButton("확인",(d,x)->r.confirm()).setNegativeButton("취소",(d,x)->r.cancel()).setOnCancelListener(d->r.cancel()).show();return true;}
 @Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(files!=null)files.onReceiveValue(null);files=cb;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);try{startActivityForResult(i,20);}catch(Exception e){files.onReceiveValue(null);files=null;toast("사진 선택 앱을 열 수 없습니다");}return true;}
 @Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){if(!ORIGIN.equals(Uri.parse(origin).getScheme()+"://"+Uri.parse(origin).getHost())){cb.invoke(origin,false,false);return;}if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED){cb.invoke(origin,true,false);}else{geo=cb;geoOrigin=origin;requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},21);}}});web.loadUrl(ORIGIN+"/index.html");}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==21&&geo!=null){boolean ok=checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;geo.invoke(geoOrigin,ok,false);geo=null;}}
 @Override protected void onActivityResult(int r,int c,Intent i){super.onActivityResult(r,c,i);if(r==20&&files!=null){Uri[] result=null;if(c==RESULT_OK&&i!=null){if(i.getClipData()!=null){ClipData d=i.getClipData();result=new Uri[d.getItemCount()];for(int n=0;n<result.length;n++)result[n]=d.getItemAt(n).getUri();}else if(i.getData()!=null)result=new Uri[]{i.getData()};}files.onReceiveValue(result);files=null;}}
 private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}
 @Override public void onBackPressed(){web.evaluateJavascript("typeof closeLightbox==='function' && document.getElementById('lightbox').classList.contains('open') ? (closeLightbox(),true) : false",v->{if(!"true".equals(v))finish();});}
 @Override protected void onPause(){web.evaluateJavascript("if(typeof saveReportState==='function')saveReportState()",null);super.onPause();}
 @Override protected void onDestroy(){if(files!=null)files.onReceiveValue(null);web.removeJavascriptInterface("ReportAndroid");web.destroy();super.onDestroy();}
 public class Bridge {@JavascriptInterface public void copyAndOpen(String text){runOnUiThread(()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("운전보고",text));Intent i=getPackageManager().getLaunchIntentForPackage("com.kakao.talk");if(i!=null){startActivity(i);toast("메시지 복사 완료 · 카톡에 붙여넣으세요");}else toast("메시지 복사 완료");});}
 @JavascriptInterface public boolean savePhoto(String data,String name){Uri uri=null;try{if(data==null||data.length()>28000000||!data.startsWith("data:image/"))return false;String mime=data.substring(5,data.indexOf(';'));String ext=mime.equals("image/png")?".png":mime.equals("image/webp")?".webp":".jpg";byte[] bytes=Base64.decode(data.substring(data.indexOf(',')+1),Base64.DEFAULT);ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name+"_"+System.currentTimeMillis()+ext);v.put(MediaStore.Images.Media.MIME_TYPE,mime);v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/FacilityReport");v.put(MediaStore.Images.Media.IS_PENDING,1);uri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(uri==null)return false;try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(bytes);}v.clear();v.put(MediaStore.Images.Media.IS_PENDING,0);getContentResolver().update(uri,v,null,null);return true;}catch(Exception e){if(uri!=null)getContentResolver().delete(uri,null,null);return false;}}
 }
}
